config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "registration", to: "registration#new"
  post "registration", to: "registration#create"

  get "login", to: "session#new"
  post "login", to: "session#create"
  delete "logout", to: "session#destroy"

  root to: "root#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
=begin
email: string -> actual, interactive
has_secure_password method creates three fields
password_digest: string -> actual, non-interactive
password: string -> virtual, interactive
passord_confirmation: string -> virtual, interactive
=end

class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Must be valid email" } 
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  
  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to login_path, notice: "You must be logged in" if Current.user.nil?
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: "If email exists, you will get a password reset link."
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to login_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to login_path, notice: "Success, Please login."
    else
      render :edit
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated!"
    else
      render :edit
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Registered successfully!!"
    else
      render :new
    end
  end

  private
  def user_params
    puts :user
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Login successfully"
    else
      flash[:alert] = "Invalid credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BufferTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="m-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="m-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password?</h1>
<%= form_with url: password_reset_path do |form| %>
  <div class="m-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/root/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to the home page</h1>
</div>

app/views/session/new.html.erb
<h1>Log in</h1>

<%= form_with url: login_path do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "dummy.com" %>
  </div>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
    <%= link_to "Forgot Password?", password_reset_path %>
  </div>
  <div class="mb-3">
    <%= form.submit "Login", data: { turbo: false }, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-danger mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "nav-link active" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-danger" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Registration", registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>